### ISSUE TITLE
Unit Test Tracking

### ISSUE THREAD

**Issue by Werni2A** [Werni2A/OpenAllegroParser#9]
Tests that should be implemented into the CI:
- [ ] `Units` (enum)
- [ ] `Decimal places` (unsigned in range [0, 4])
- `Start`
  - [x] `Padstack usage` (enum)
- `Drill`
  - `Drill hole`
    - [ ] `Hole type` (enum)
    - [ ] `Finished diameter` (unsigned)
    - [ ] `+ Tolerance` (unsigned)
    - [ ] `- Tolerance` (unsigned)
    - [ ] `Drill tool size` (string)
    - [ ] `Non-standard drill` (enum)
  - `Hole plating`
    - [ ] `Hole/slot plating` (enum) 
  - `Define the drill rows and columns`
    - [ ] `Number of drill rows` (unsigned)
    - [ ] `Number of drill columns` (unsigned)
    - [ ] `Clearance between columns` (unsigned)
    - [ ] `Clearance between rows` (unsigned)
    - [ ] `Drills are staggered` (bool)
- `Secondary Drill`
  - [ ] `Backdrill` (bool)
    - [ ] `Diameter` (unsigned)
      - `Backdrill drill symbol`
        - [ ] `Type of drill figure` (enum)
        - [ ] `Characters` (string with 3 characters)
        - [ ] `Drill figure width` (unsigned)
        - [ ] `Drill figure height` (unsigned)
  - [ ] `Counter bore/sink` (bool)
    - [ ] Bore type (enum)
    - [ ] `Diameter` (unsigned)
    - [ ] `+ Tolerance` (unsigned)
    - [ ] `- Tolerance` (unsigned)
    - [ ] `Depth` (unsigned)
- `Drill Symbol`
